services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home
    networks:
      jenkins:
        ipv4_address: 172.24.0.3  
  agent:
    image: jenkins/slave15
    build: 
      context: .
      dockerfile: ./SlaveDockerFile 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      jenkins:
        ipv4_address: 172.24.0.2  
  nginx:
    image: nginx
    container_name: nginx_cicd
    ports:
      - 8000:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      jenkins:
        ipv4_address: 172.24.0.4   
  app1:
    image: youssefshebl/vueapp
    container_name: app1    
    networks:
      jenkins:
        ipv4_address: 172.24.0.5    
  app2:
    image: youssefshebl/vueapp
    container_name: app2    
    networks:
      jenkins:
        ipv4_address: 172.24.0.6                    



networks:
  jenkins:
    driver: bridge
    ipam:
     config:
       - subnet: 172.24.0.0/24
         gateway: 172.24.0.1